import React, { useState } from 'react';
import { Lightbulb, Users, Target, CheckCircle, ArrowRight, Download, Sparkles } from 'lucide-react';

const PRDBuilder = () => {
  const [currentStep, setCurrentStep] = useState(0);
  const [formData, setFormData] = useState({
    title: '',
    problem: '',
    solution: '',
    objectives: [],
    userStories: [],
    requirements: []
  });

  const steps = [
    { title: 'Problem Definition', icon: Target },
    { title: 'Solution Overview', icon: Lightbulb },
    { title: 'User Stories', icon: Users },
    { title: 'Requirements', icon: CheckCircle }
  ];

  const aiSuggestions = {
    0: [
      "Consider framing the problem from the user's perspective",
      "Include quantitative data about the problem's impact",
      "Mention competitive landscape or market opportunity"
    ],
    1: [
      "Describe the core value proposition clearly",
      "Outline the main user journey or workflow",
      "Consider technical feasibility and constraints"
    ],
    2: [
      "Write stories in 'As a [user], I want [goal] so that [benefit]' format",
      "Prioritize stories by user value and business impact",
      "Include edge cases and error scenarios"
    ],
    3: [
      "Separate functional and non-functional requirements",
      "Include success metrics and acceptance criteria",
      "Consider security, performance, and accessibility"
    ]
  };

  const generateAISuggestion = (step: number, content: string) => {
    const suggestions: Record<number, string[]> = {
      0: [
        "Based on industry trends, consider adding user pain points around mobile experience",
        "This problem aligns with common SaaS challenges. Consider mentioning scalability concerns",
        "Great problem statement! You might want to add specific user segments affected"
      ],
      1: [
        "Your solution approach looks solid. Consider how this integrates with existing workflows",
        "This solution could benefit from a phased rollout approach",
        "Excellent direction! Think about measuring user adoption metrics"
      ]
    };
    
    return suggestions[step] ? suggestions[step][Math.floor(Math.random() * suggestions[step].length)] : "Keep refining your content!";
  };

  const handleNext = () => {
    if (currentStep < steps.length - 1) {
      setCurrentStep(currentStep + 1);
    }
  };

  const handlePrevious = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1);
    }
  };

  const updateFormData = (field: string, value: any) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const exportPRD = () => {
    const prdContent = `
# ${formData.title || 'Product Requirements Document'}

## Problem Statement
${formData.problem || 'Problem definition needed...'}

## Solution Overview
${formData.solution || 'Solution description needed...'}

## User Stories
${formData.userStories.map((story: string, i: number) => `${i + 1}. ${story}`).join('\n') || 'User stories needed...'}

## Requirements
${formData.requirements.map((req: string, i: number) => `${i + 1}. ${req}`).join('\n') || 'Requirements needed...'}

## Success Metrics
- User adoption rate
- Feature usage metrics
- User satisfaction scores
- Business impact measurements

---
*Generated by PM Copilot AI Assistant*
    `.trim();

    const blob = new Blob([prdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${formData.title || 'PRD'}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto">
      {/* Header */}
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-8">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">AI-Powered PRD Builder</h2>
            <p className="text-gray-600 mt-1">Create comprehensive PRDs with intelligent guidance</p>
          </div>
          <button
            onClick={exportPRD}
            className="flex items-center space-x-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
          >
            <Download className="h-4 w-4" />
            <span>Export PRD</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Main Content */}
        <div className="lg:col-span-2">
          {/* Progress Steps */}
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 mb-6">
            <div className="flex items-center justify-between">
              {steps.map((step, index) => (
                <div key={index} className="flex items-center">
                  <div className={`flex items-center justify-center w-8 h-8 rounded-full ${
                    index === currentStep ? 'bg-blue-600 text-white' :
                    index < currentStep ? 'bg-green-500 text-white' :
                    'bg-gray-200 text-gray-400'
                  }`}>
                    {index < currentStep ? (
                      <CheckCircle className="h-4 w-4" />
                    ) : (
                      <step.icon className="h-4 w-4" />
                    )}
                  </div>
                  <span className={`ml-2 text-sm font-medium ${
                    index === currentStep ? 'text-blue-600' :
                    index < currentStep ? 'text-green-600' :
                    'text-gray-400'
                  }`}>
                    {step.title}
                  </span>
                  {index < steps.length - 1 && (
                    <ArrowRight className="h-4 w-4 text-gray-300 mx-4" />
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Step Content */}
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
            {currentStep === 0 && (
              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    PRD Title
                  </label>
                  <input
                    type="text"
                    value={formData.title}
                    onChange={(e) => updateFormData('title', e.target.value)}
                    placeholder="e.g., Mobile App Push Notifications Feature"
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Problem Statement
                  </label>
                  <textarea
                    value={formData.problem}
                    onChange={(e) => updateFormData('problem', e.target.value)}
                    rows={6}
                    placeholder="Describe the user problem you're solving..."
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  />
                </div>
              </div>
            )}

            {currentStep === 1 && (
              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Solution Overview
                  </label>
                  <textarea
                    value={formData.solution}
                    onChange={(e) => updateFormData('solution', e.target.value)}
                    rows={6}
                    placeholder="Describe your proposed solution..."
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  />
                </div>
              </div>
            )}

            {currentStep === 2 && (
              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    User Stories
                  </label>
                  <div className="space-y-3">
                    {formData.userStories.map((story: string, index: number) => (
                      <div key={index} className="flex items-center space-x-3">
                        <input
                          type="text"
                          value={story}
                          onChange={(e) => {
                            const newStories = [...formData.userStories];
                            newStories[index] = e.target.value;
                            updateFormData('userStories', newStories);
                          }}
                          placeholder="As a [user], I want [goal] so that [benefit]"
                          className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        />
                      </div>
                    ))}
                    <button
                      onClick={() => updateFormData('userStories', [...formData.userStories, ''])}
                      className="w-full px-4 py-2 border border-dashed border-gray-300 rounded-lg text-gray-600 hover:border-gray-400 hover:text-gray-700 transition-colors"
                    >
                      + Add User Story
                    </button>
                  </div>
                </div>
              </div>
            )}

            {currentStep === 3 && (
              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Requirements
                  </label>
                  <div className="space-y-3">
                    {formData.requirements.map((req: string, index: number) => (
                      <div key={index} className="flex items-center space-x-3">
                        <input
                          type="text"
                          value={req}
                          onChange={(e) => {
                            const newReqs = [...formData.requirements];
                            newReqs[index] = e.target.value;
                            updateFormData('requirements', newReqs);
                          }}
                          placeholder="Functional or non-functional requirement"
                          className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        />
                      </div>
                    ))}
                    <button
                      onClick={() => updateFormData('requirements', [...formData.requirements, ''])}
                      className="w-full px-4 py-2 border border-dashed border-gray-300 rounded-lg text-gray-600 hover:border-gray-400 hover:text-gray-700 transition-colors"
                    >
                      + Add Requirement
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Navigation */}
            <div className="flex justify-between mt-8 pt-6 border-t border-gray-200">
              <button
                onClick={handlePrevious}
                disabled={currentStep === 0}
                className={`px-4 py-2 rounded-lg transition-colors ${
                  currentStep === 0
                    ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                }`}
              >
                Previous
              </button>
              <button
                onClick={handleNext}
                disabled={currentStep === steps.length - 1}
                className={`px-4 py-2 rounded-lg transition-colors ${
                  currentStep === steps.length - 1
                    ? 'bg-gray-100 text-gray-400 cursor-not-allowed'
                    : 'bg-blue-600 text-white hover:bg-blue-700'
                }`}
              >
                Next Step
              </button>
            </div>
          </div>
        </div>

        {/* AI Assistant Sidebar */}
        <div className="lg:col-span-1">
          <div className="bg-gradient-to-br from-purple-50 to-blue-50 rounded-lg p-6 border border-purple-200">
            <div className="flex items-center space-x-2 mb-4">
              <Sparkles className="h-5 w-5 text-purple-600" />
              <h3 className="font-semibold text-purple-900">AI Assistant</h3>
            </div>
            
            <div className="space-y-4">
              <div className="bg-white/60 rounded-lg p-4">
                <h4 className="font-medium text-purple-900 mb-2">Smart Suggestions</h4>
                <ul className="text-sm text-purple-700 space-y-2">
                  {aiSuggestions[currentStep as keyof typeof aiSuggestions]?.map((suggestion, index) => (
                    <li key={index} className="flex items-start space-x-2">
                      <span className="text-purple-400 mt-1">•</span>
                      <span>{suggestion}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="bg-white/60 rounded-lg p-4">
                <h4 className="font-medium text-purple-900 mb-2">Best Practices</h4>
                <p className="text-sm text-purple-700">
                  {currentStep === 0 && "Focus on user pain points and business impact. Use data to support your problem statement."}
                  {currentStep === 1 && "Clearly articulate the value proposition and how it solves the identified problem."}
                  {currentStep === 2 && "Write user stories from the perspective of different user personas and prioritize by value."}
                  {currentStep === 3 && "Include both functional requirements and success criteria. Don't forget non-functional requirements."}
                </p>
              </div>

              <div className="bg-white/60 rounded-lg p-4">
                <h4 className="font-medium text-purple-900 mb-2">Progress Insight</h4>
                <p className="text-sm text-purple-700">
                  You're {Math.round(((currentStep + 1) / steps.length) * 100)}% complete with your PRD. 
                  Keep going - you're building something great! 🚀
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PRDBuilder;